name: Stacy and Ryan are getting married.
author: Ryan Fisher
meta_description: We're getting married. We're pretty excited! You can find a bit about our wedding here.

google_analytics_id: UA-20742253-6

pygments: true

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'Rakefile', '.gitignore']
